// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/albertsundjaja/frankie/models"
)

// USDKCheckOKCode is the HTTP code returned for type USDKCheckOK
const USDKCheckOKCode int = 200

/*USDKCheckOK The data is fine. No issues, and everyone gets a puppy.

swagger:response uSDKCheckOK
*/
type USDKCheckOK struct {

	/*
	  In: Body
	*/
	Payload *models.PuppyObject `json:"body,omitempty"`
}

// NewUSDKCheckOK creates USDKCheckOK with default headers values
func NewUSDKCheckOK() *USDKCheckOK {

	return &USDKCheckOK{}
}

// WithPayload adds the payload to the u s d k check o k response
func (o *USDKCheckOK) WithPayload(payload *models.PuppyObject) *USDKCheckOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the u s d k check o k response
func (o *USDKCheckOK) SetPayload(payload *models.PuppyObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *USDKCheckOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// USDKCheckInternalServerErrorCode is the HTTP code returned for type USDKCheckInternalServerError
const USDKCheckInternalServerErrorCode int = 500

/*USDKCheckInternalServerError The system is presently unavailable, or running in a severely degraded state. Check the error message for details

swagger:response uSDKCheckInternalServerError
*/
type USDKCheckInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorObject `json:"body,omitempty"`
}

// NewUSDKCheckInternalServerError creates USDKCheckInternalServerError with default headers values
func NewUSDKCheckInternalServerError() *USDKCheckInternalServerError {

	return &USDKCheckInternalServerError{}
}

// WithPayload adds the payload to the u s d k check internal server error response
func (o *USDKCheckInternalServerError) WithPayload(payload *models.ErrorObject) *USDKCheckInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the u s d k check internal server error response
func (o *USDKCheckInternalServerError) SetPayload(payload *models.ErrorObject) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *USDKCheckInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
