// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Frankie Financial Universal SDK Tester API (Internal Only)
//
//  ------
//  This API allows developers to test the Universal SDK output to ensure it looks right..
//  ------
//  The traditional Swagger view of this documentation can be found here:
//    - https://app.swaggerhub.com/apis-docs/FrankieFinancial/TestUniversalSDK/
//
//
//  Schemes:
//    https
//  Host: localhost
//  BasePath: /
//  Version: 1.0.3
//  Contact: <dev@frankiefinancial.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
