// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// KeyValuePairObject Individual key-value pair
//
// swagger:model KeyValuePairObject
type KeyValuePairObject struct {

	// Name of the data
	KvpKey string `json:"kvpKey,omitempty"`

	// kvp type
	KvpType EnumKVPType `json:"kvpType,omitempty"`

	// Value of the data
	KvpValue string `json:"kvpValue,omitempty"`
}
